###최종쿼리다
SELECT * FROM (SELECT I_NEWPRODUCTNAME, I_L1NAME, I_NEWMAINPROG, I_BASEDT, I_TIMESPAN, row_number() over (PARTITION BY I_NEWPRODUCTNAME ORDER BY I_TIMESPAN asc) RankNo FROM I_PRODUCT) T WHERE RankNO =1 and I_NEWPRODUCTNAME LIKE '%YOKE%'


SELECT L1NAME, NEWPRODUCTNAME, NEWMAINPROG, MIN(TIMESPAN), BASEDT FROM TM_PRODUCT WHERE NEWPRODUCTNAME LIKE  '%YOKE%'


SELECT MIN(TIMESPAN) FROM TM_PRODUCT WHERE NEWPRODUCTNAME LIKE  '%YOKE%'

SELECT L1NAME, NEWPRODUCTNAME, NEWMAINPROG, TIMESPAN, BASEDT FROM TM_PRODUCT WHERE NEWPRODUCTNAME LIKE  '%YOKE%' = (SELECT MIN(TIMESPAN) FROM NEWPRODUCTNAME

SELECT L1NAME, NEWPRODUCTNAME, NEWMAINPROG, MIN(TIMESPAN), BASEDT AS TIMESPAN FROM TM_PRODUCT GROUP BY L1NAME WHERE NEWPRODUCTNAME LIKE  '%YOKE%'

Select CD_PLANT FROM TABLE_PLANT WHERE CD_PLANT IN(SELECT CD_PLANT FROM  TABLE_PLANT WHERE PLANT ='1000' AND COMPANY = '0327')

#이것도 되고
SELECT NEWPRODUCTNAME, L1NAME, NEWMAINPROG, TIMESPAN, BASEDT FROM TM_PRODUCT WHERE NEWPRODUCTNAME IN (SELECT NEWPRODUCTNAME FROM TM_PRODUCT WHERE NEWPRODUCTNAME LIKE '%YOKE%') ORDER BY NEWPRODUCTNAME

#이것도 된다
SELECT NEWPRODUCTNAME, L1NAME, NEWMAINPROG, TIMESPAN, BASEDT FROM TM_PRODUCT WHERE NEWPRODUCTNAME IN (SELECT NEWPRODUCTNAME FROM TM_PRODUCT WHERE NEWPRODUCTNAME LIKE '%YOKE%')

#테스트중(안됨)
SELECT NEWPRODUCTNAME, L1NAME, NEWMAINPROG, TIMESPAN, BASEDT FROM TM_PRODUCT WHERE TIMESPAN IN (SELECT MIN(TIMESPAN), NEWPRODUCTNAME FROM TM_PRODUCT WHERE NEWPRODUCTNAME LIKE '%YOKE%')

#테스트중(되긴하는데 이상함)
SELECT NEWPRODUCTNAME, L1NAME, NEWMAINPROG, TIMESPAN, BASEDT FROM TM_PRODUCT WHERE TIMESPAN <= (SELECT AVG(TIMESPAN) FROM TM_PRODUCT WHERE NEWPRODUCTNAME LIKE '%YOKE%')

#테스트중(뭔가이상)
SELECT I_NEWPRODUCTNAME, I_L1NAME, I_NEWMAINPROG, I_TIMESPAN, I_BASEDT FROM I_PRODUCT WHERE I_TIMESPAN > any (SELECT I_TIMESPAN FROM I_PRODUCT WHERE I_NEWPRODUCTNAME LIKE '%YOKE%')

#테스트중(안됨)
SELECT I_NEWPRODUCTNAME, I_L1NAME, I_NEWMAINPROG, I_TIMESPAN, I_BASEDT FROM I_PRODUCT WHERE I_NEWPRODUCTNAME, > any (SELECT I_TIMESPAN FROM I_PRODUCT)

#테스트중(안됨)
SELECT I_NEWPRODUCTNAME, I_L1NAME, I_NEWMAINPROG, I_TIMESPAN, I_BASEDT FROM I_PRODUCT WHERE I_TIMESPAN <= (SELECT AVG(I_TIMESPAN) FROM I_PRODUCT) ORDER BY I_NEWPRODUCTNAME

#테스트중(이상함)
SELECT I_NEWPRODUCTNAME, I_L1NAME, I_NEWMAINPROG, AVG(I_TIMESPAN), I_BASEDT FROM I_PRODUCT GROUP BY I_NEWPRODUCTNAME,I_L1NAME,I_BASEDT,I_NEWMAINPROG,I_TIMESPAN

#테스트중(이걸로하자)
SELECT I_NEWPRODUCTNAME, I_L1NAME, AVG(I_TIMESPAN) AS NEWTIMESPAN FROM I_PRODUCT GROUP BY I_NEWPRODUCTNAME, I_L1NAME ORDER BY I_NEWPRODUCTNAME

#테스트중(다른쿼리방식)
SELECT * FROM (SELECT I_NEWPRODUCTNAME, I_L1NAME, I_NEWMAINPROG, I_BASEDT, I_TIMESPAN, row_number() over (PARTITION BY I_NEWPRODUCTNAME ORDER BY I_TIMESPAN desc) RankNo FROM I_PRODUCT) T WHERE RankNO =1


SELECT NEWPRODUCTNAME, L1NAME, NEWMAINPROG, MIN(TIMESPAN), BASEDT FROM TM_PRODUCT WHERE NEWPRODUCTNAME IN (SELECT NEWPRODUCTNAME FROM TM_PRODUCT WHERE NEWPRODUCTNAME LIKE '%YOKE%') ORDER BY NEWPRODUCTNAME